name: Matrix Example (main)
on: push
jobs:
  build-watcher:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - { runner: macos-latest, os: darwin, arch: amd64, tags: netcgo }
          - { runner: macos-latest, os: darwin, arch: arm64, tags: netcgo }
          - {
              runner: ubuntu-latest,
              os: linux,
              arch: amd64,
              env: CGO_ENABLED=0,
            }
          - {
              runner: ubuntu-latest,
              os: linux,
              arch: amd64,
              env: CGO_ENABLED=0,
            }
          - {
              runner: ubuntu-latest,
              os: windows,
              arch: amd64,
              env: CGO_ENABLED=0,
            }
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: hashicorp/actions-go-build@main
        with:
          product_name: mediacms-watcher
          product_version: 0.0.1
          go_version: 1.22
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
          instructions: |-
            ${{ matrix.env }} \
              go build \
                -o "$BIN_PATH" \
                -trimpath \
                -buildvcs=false \
                -tags="${{ matrix.tags }}" \
                -ldflags "
                  -X 'main.Version=$PRODUCT_VERSION'
                  -X 'main.Revision=$PRODUCT_REVISION'
                  -X 'main.RevisionTime=$PRODUCT_REVISION_TIME'
                  "
  release:
    needs: build-watcher
    runs-on: ubuntu-latest
    steps:
      # Download the release binary (arfiact) from the build-watcher job
      - name: Download release binary
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: ${{ github.workspace }}/*
